[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile.railway"
buildCommand = "echo 'Building production HandyWriterzAI'"

[deploy]
startCommand = "cd backend && uvicorn src.main:app --host 0.0.0.0 --port $PORT --workers 2"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Production environment variables
[env]
NODE_ENV = "production"
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"

# Core system configuration - no simple system
SIMPLE_SYSTEM_AVAILABLE = "false"
ADVANCED_SYSTEM_AVAILABLE = "true"

# Production security and reliability
FEATURE_REGISTRY_ENFORCED = "true"
BUDGET_STRICT_MODE = "true"
FEATURE_SSE_PUBLISHER_UNIFIED = "true"
FEATURE_DOUBLE_PUBLISH_SSE = "false"

# Performance and scaling
MAX_WORKERS = "2"
WORKER_TIMEOUT = "300"
KEEPALIVE = "2"

# Logging
LOG_LEVEL = "INFO"
STRUCTURED_LOGGING = "true"