# Logical model ID mappings - replaces hardcoded aliases
logical_models:
  o3-reasoner:
    provider: openai
    model_id: o1-preview
    description: "Advanced reasoning model for complex tasks"
    
  o3-reasoner-mini:
    provider: openai
    model_id: o1-mini
    description: "Lightweight reasoning model"
    
  sonar-deep:
    provider: perplexity
    model_id: llama-3.1-sonar-large-128k-online
    description: "Deep web search with large context"
    
  sonar-fast:
    provider: perplexity
    model_id: llama-3.1-sonar-small-128k-online
    description: "Fast web search"
    
  gemini-pro:
    provider: gemini
    model_id: gemini-pro
    description: "Google's flagship model"
    
  gemini-flash:
    provider: gemini
    model_id: gemini-1.5-flash
    description: "Fast Gemini model"
    
  gemini-2.5-pro:
    provider: gemini
    model_id: gemini-2.0-flash-exp
    description: "Latest Gemini experimental model"
    
  gemini-2.5-flash:
    provider: gemini
    model_id: gemini-1.5-flash
    description: "Fast Gemini flash model"
    
  claude-opus:
    provider: anthropic
    model_id: claude-3-opus-20240229
    description: "Most capable Claude model"
    
  claude-sonnet:
    provider: anthropic
    model_id: claude-3-sonnet-20240229
    description: "Balanced Claude model"
    
  claude-haiku:
    provider: anthropic
    model_id: claude-3-haiku-20240307
    description: "Fast Claude model"
    
  kimi-k2:
    provider: openrouter
    model_id: deepseek/deepseek-chat
    description: "Alternative reasoning model"

defaults:
  writer: gemini-2.5-pro
  formatter: gemini-2.5-flash
  search_primary: o3-reasoner
  search_secondary: sonar-deep
  search_fallback: kimi-k2
  qa: o3-reasoner-mini
  evaluator: claude-opus
  evaluator_advanced: claude-opus

override_allowlist:
  - writer
  - search_primary
  - evaluator
  - evaluator_advanced

budget:
  free: { daily_usd: 0.50, max_model: o3-reasoner }
  pro:  { daily_usd: 5.00, max_model: sonar-deep }
  enterprise: { daily_usd: 50, max_model: claude-opus }
